blog/urls.py
from django.urls import path

from .views import ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleListView, ArticleUpdateView

urlpatterns = [
    path("articles_list/", ArticleListView.as_view(), name="articles_list"),
    path("article_create/", ArticleCreateView.as_view(), name="article_create"),
    path("article_detail/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("article_update/<int:pk>/", ArticleUpdateView.as_view(), name="article_update"),
    path("article_confirm_delete/<int:pk>/", ArticleDeleteView.as_view(), name="article_delete"),
]

catalog/urls.py
from django.urls import path

from .views import (CategoryDetailView, ContactsView, HomeListView, ProductCreateView, ProductDeleteView,
                    ProductDetailView, ProductUpdateView, UnpublishedProductsListView, UnpublishProductView)

app_name = "catalog"

urlpatterns = [
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("home/", HomeListView.as_view(), name="home"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="single_product"),
    path("add_product/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("product/<int:pk>/unpublish/", UnpublishProductView.as_view(), name="unpublish_product"),
    path("unpublished_products/", UnpublishedProductsListView.as_view(), name="unpublished_products"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import CustomLoginView, CustomLogoutView, RegisterView

app_name = "users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True, verbose_name="Номер телефона")
    avatar = models.ImageField(upload_to="avatars", blank=True, null=True, verbose_name="Аватар")
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name="Страна")

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ["email",]

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ("email", "password1", "password2")

users/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from .forms import CustomUserCreationForm


class CustomLoginView(LoginView):
    template_name = "login.html"
    success_url = reverse_lazy("catalog:home")


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy("catalog:home")


class RegisterView(FormView):
    form_class = CustomUserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.send_welcome_email(user.email)
        return super().form_valid(form)

    def send_welcome_email(self, user_email):
        subject = "Поздравляем с регистрацией!"
        message = """Примите наши поздравления с регистрацией в нашем сервисе! 
        Теперь вы можете просматривать продукты и управлять ими"""
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)

users/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include "catalog/includes/header.html" %}
  {% block content %} {% endblock %}
  <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
</footer>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</body>
</html>

users/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}
<h2>Вход</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Войти</button>
</form>
{% endblock %}

users/templates/logout.html
{% extends "base.html" %}

{% block title %} Logout {% endblock %}

{% block content %}
<h2> Вы вышли из системы </h2>
<p>Если хотите войти снова, нажмите на кнопку снизу</p>
<a href="{% url 'users:login' %}"><button class="btn btn-primary">Войти</button></a>
{% endblock %}

users/templates/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}