blog/urls.py
from django.urls import path

from .views import ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleListView, ArticleUpdateView

urlpatterns = [
    path("articles_list/", ArticleListView.as_view(), name="articles_list"),
    path("article_create/", ArticleCreateView.as_view(), name="article_create"),
    path("article_detail/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("article_update/<int:pk>/", ArticleUpdateView.as_view(), name="article_update"),
    path("article_confirm_delete/<int:pk>/", ArticleDeleteView.as_view(), name="article_delete"),
]

catalog/urls.py
from django.urls import path

from .views import (CategoryDetailView, ContactsView, HomeListView, ProductCreateView, ProductDeleteView,
                    ProductDetailView, ProductUpdateView, UnpublishedProductsListView, UnpublishProductView)

app_name = "catalog"

urlpatterns = [
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("home/", HomeListView.as_view(), name="home"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="single_product"),
    path("add_product/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("product/<int:pk>/unpublish/", UnpublishProductView.as_view(), name="unpublish_product"),
    path("unpublished_products/", UnpublishedProductsListView.as_view(), name="unpublished_products"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import CustomUser


class Category(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Название", help_text="Введите название категории", unique=True
    )
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название", help_text="Введите название продукта")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(
        upload_to="products",
        blank=True,
        null=True,
        verbose_name="Изображение",
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    price = models.FloatField(verbose_name="Цена")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    is_published = models.BooleanField(default=False)
    owner = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="products", verbose_name="Владелец", null=True, blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["category", "name"]
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]


class Contact(models.Model):
    country = models.CharField(max_length=100, verbose_name="Страна")
    individual_number = models.CharField(max_length=100, verbose_name="ИНН")
    address = models.TextField(verbose_name="Адрес")

    def __str__(self):
        return f"{self.country} {self.address}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"
        ordering = ["country", "address"]

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models import Product

FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "обман",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ["created_at", "updated_at", "is_published", "owner"]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите название продукта"})
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание продукта"}
        )
        self.fields["image"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Выберите изображение продукта"}
        )

        self.fields["category"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Выберите категорию продукта"}
        )
        self.fields["price"].widget.attrs.update({"class": "form-control", "placeholder": "Введите цену продукта"})

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if any(word in name.lower() for word in FORBIDDEN_WORDS):
            raise ValidationError("Название содержит запрещенные слова")
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in FORBIDDEN_WORDS):
            raise ValidationError("Описание содержит запрещенные слова")
        return description

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Цена не может быть отрицательной")
        return price

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image:
            if image.size > 5 * 1024 * 1024:
                raise ValidationError("Размер изображения не должен превышать 5 Мб")

            if hasattr(image.file, "content_type") and image.file.content_type not in ["image/jpeg", "image/png"]:
                raise ValidationError("Формат изображения должен быть JPEG или PNG")
        return image

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView, View

from .forms import ProductForm
from .models import Category, Contact, Product
from .services import ProductService

ALL_CATEGORIES = ProductService.get_all_categories()


class ContactsView(TemplateView):
    model = Contact
    template_name = "catalog/contacts.html"

    def get(self, request):
        all_contacts = Contact.objects.all()
        context = {"categories": ALL_CATEGORIES, "contacts": all_contacts}

        return render(request, "catalog/contacts.html", context)

    def post(self, request):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        return HttpResponse(
            f"""Спасибо, {name}!
                Мы получили ваше сообщение: ({message}).
                Мы перезвоним вам по телефону: {phone}"""
        )


class HomeListView(ListView):
    model = Product
    context_object_name = "products"

    def get_queryset(self):
        queryset = cache.get("products")  # Попытка получить данные из кэша
        if not queryset:
            queryset = super().get_queryset()
            cache.set("products", queryset, 60 * 15)  # Сохранение данных в кэш
        return queryset

    def get(self, request):
        published_products = Product.objects.filter(is_published=True)
        paginator = Paginator(published_products, 4)  # Show 4 products per page

        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context = {"products": page_obj, "categories": ALL_CATEGORIES}
        return render(request, "catalog/home.html", context)


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = "products"
    template_name = "catalog/category.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.object.id
        context["products"] = ProductService.get_products_in_category(category_id)
        context["categories"] = ALL_CATEGORIES
        return context


class UnpublishedProductsListView(ListView):
    model = Product
    context_object_name = "products"

    def get(self, request):
        unpublished_products = Product.objects.filter(is_published=False)
        paginator = Paginator(unpublished_products, 4)  # Show 4 products per page

        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context = {"products": page_obj, "categories": ALL_CATEGORIES}
        return render(request, "catalog/home.html", context)


class UnpublishProductView(LoginRequiredMixin, View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)

        if not request.user.has_perm("products.can_unpublish_product"):
            return HttpResponseForbidden("У вас нет прав на снятие товара с публикации")

        product.is_published = False if product.is_published else True
        product.save()
        return redirect("catalog:home")


@method_decorator(cache_page(60 * 15), name="dispatch")
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/single_product.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = ALL_CATEGORIES
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    context_object_name = "product"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    context_object_name = "product"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):

        if form.instance.owner == self.request.user:
            return super().form_valid(form)

        return HttpResponseForbidden("У вас нет прав доступа для редактирования продукта")


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    permission_required = "products.delete_product"
    model = Product
    context_object_name = "product"
    template_name = "catalog/product_confirm_delete.html"
    success_url = reverse_lazy("catalog:home")

    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)

        if not request.user.has_perm("delete_product") and not request.user == product.owner:
            return HttpResponseForbidden("У вас нет прав на удаление продукта!")

        product.delete()
        return redirect("catalog:home")

catalog/templates/catalog/add_product.html
{% extends "catalog/base.html" %}

{% block title %}Add product{% endblock %}

{% block content %}

<div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Добавление продукта</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Добавить продукт</button>
                        <a href="{% url "home" %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>

{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include "catalog/includes/header.html" %}
{% block content %} {% endblock %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
<script type="text/javascript" src="/static/js/bootstrap.bundle.js"></script>
</body>
</html>

catalog/templates/catalog/category.html
{% extends "catalog/base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Онлайн магазин для самых разнообразных товаров</p>
</div>


<div class="container">
    <div class="row text-center">
        <div class="row row-cols-2 row-cols-md-4 g-4">
            {% for product in products %}
            {% if product.is_published %}
            <div class="col">
                <div class="card mb-4 box-shadow">
                    {% if product.image %}
                    <img src="{{ product.image | media_filter }}" alt="{{ product.name }}"
                         class="card-img-top img-fluid">
                    {% else %}
                    <img src="{% static 'placeholder.png'%}" alt="{{ product.name }}" class="card-img-top img-fluid">
                    {% endif %}
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ product.price }}$</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-6">
                            <li><b>Категория: </b>{{ product.category }}</li>
                            <li><b>Описание: </b>{{ product.description|truncatechars:100 }}</li>
                            <li><b>Владелец: </b>{{ product.owner }}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">
                            <a href="{% url 'catalog:single_product' product.pk %}"
                               class="link-underline-light link-underline-opacity-0">Посмотреть</a>
                        </button>
                    </div>
                </div>

            </div>
            {% endif %}
            {% endfor %}
        </div>

    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            <li class="page-item {% if products.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends "catalog/base.html" %}

{% block title %}Contacts{% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        {% for contact in contacts %}
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{ contact.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{ contact.individual_number }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ contact.address }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends "catalog/base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}Skystore{% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Онлайн магазин для самых разнообразных товаров</p>
</div>


<div class="container">
    <div class="row text-center">
        <div class="row row-cols-2 row-cols-md-4 g-4">
            {% for product in products %}

            <div class="col">
                <div class="card mb-4 box-shadow">
                    {% if product.image %}
                    <img src="{{ product.image | media_filter }}" alt="{{ product.name }}"
                         class="card-img-top img-fluid">
                    {% else %}
                    <img src="{% static 'placeholder.png'%}" alt="{{ product.name }}" class="card-img-top img-fluid">
                    {% endif %}
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ product.price }}$</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-6">
                            <li><b>Категория: </b>{{ product.category }}</li>
                            <li><b>Описание: </b>{{ product.description|truncatechars:100 }}</li>
                            <li><b>Владелец: </b>{{ product.owner }}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">
                            <a href="{% url 'catalog:single_product' product.pk %}"
                               class="link-underline-light link-underline-opacity-0">Посмотреть</a>
                        </button>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>

    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for num in products.paginator.page_range %}
            <li class="page-item {% if products.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends "catalog/base.html" %}

{% block title %}Удалить Продукт{% endblock %}

{% block content %}
<body>
<div class="container mt-5">
    <h1 class="mb-4">Удалить Продукт</h1>
    <p>Вы уверены, что хотите удалить "{{product.name}}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends "catalog/base.html" %}

{% block title %}Add product{% endblock %}

{% block content %}

<div class="card mb-4 box-shadow">
    <div class="card-header">
        {% if not product %}
        <h4 class="my-0 font-weight-normal">Добавление продукта</h4>
        {% else %}
        <h4 class="my-0 font-weight-normal">Обновление продукта</h4>
        {% endif %}

    </div>
    <div class="card-body">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            {% if not product %}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Добавить продукт</button>
            {% else %}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Обновить продукт</button>
            {% endif %}
            <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/single_product.html
{% extends "catalog/base.html" %}
{% load my_tags %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="card text-center">
            <div class="d-flex justify-content-center align-items-center">
                <img src="{{ product.image | media_filter }}" class="card-img-top img-fluid"
                     style="width: 300px; height: 300px;" alt="{{ product.name }}">
            </div>
            <div class="card-header">
                <h2>{{ product.name }}</h2>
                <p class="card-text"><small class="text-body-danger"><b>Добавлено:</b>
                    {{ product.created_at|date:"d.m.Y" }}</small></p>
            </div>
            <div class="card-body">
                <h3 class="card-title pricing-card-title">{{ product.price }}$</h3>
                <ul class="list-unstyled mt-3 mb-4 text-start m-6">
                    <li><b>Категория: </b> {{ product.category }}</li>
                    <li><b>Описание: </b> {{ product.description }}</li>
                    <li><b>Владелец: </b>{{ product.owner }}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                {% if product.owner == user %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_update' product.pk %}">Редактировать
                </a>
                <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:product_delete' product.pk %}">Удалить
                </a>
                {% endif %}
                {% if product.is_published %}
                <form action="{% url 'catalog:unpublish_product' product.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="p-2 btn btn-outline-info">Изъять
                        продукт из каталога
                    </button>
                </form>
                {% else %}
                <form action="{% url 'catalog:unpublish_product' product.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="p-2 btn btn-outline-info">Опубликовать продукт</button>
                </form>
                {% endif %}
            </div>
            <div class="card-footer text-body-secondary">
                Продукт был обновлен: {{product.updated_at|date:"d.m.Y"}}
            </div>
        </div>
    </div>
</div>

{% endblock %}